# Generated by Django 5.0.6 on 2024-07-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ananthapuri", "0002_departments"),
    ]

    operations = [
        migrations.AddField(
            model_name="departments",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="department_images/"
            ),
        ),
    ]
