# Generated by Django 5.0.6 on 2024-07-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ananthapuri", "0004_department_page_testimonials"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="Gallery/")),
            ],
        ),
    ]
