# Generated by Django 5.0.6 on 2024-07-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ananthapuri", "0005_gallery"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("phone_number", models.CharField(max_length=15)),
                ("description", models.TextField()),
            ],
        ),
    ]
