# Generated by Django 5.0.6 on 2024-07-04 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ananthapuri", "0006_formdata"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FormData",
        ),
    ]
