# Generated by Django 5.0.6 on 2024-07-04 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ananthapuri", "0008_formentry"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FormEntry",
        ),
    ]
