# Generated by Django 5.0.6 on 2024-07-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ananthapuri", "0009_delete_formentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="blogs/")),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
    ]
