# Generated by Django 5.0.6 on 2024-07-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ananthapuri", "0010_blog"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="Banner",
            field=models.ImageField(
                default="blogs/default_banner.jpg", upload_to="blogs/"
            ),
        ),
    ]
