# Generated by Django 5.0.6 on 2024-07-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ananthapuri", "0011_blog_banner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teachers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=15)),
                ("Image", models.ImageField(upload_to="Teachers/")),
                ("Designation", models.CharField(max_length=15)),
            ],
        ),
    ]
