# Generated by Django 5.0.6 on 2024-07-10 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ananthapuri", "0012_teachers"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Department_Page",
        ),
        migrations.DeleteModel(
            name="Departments",
        ),
        migrations.DeleteModel(
            name="Feature",
        ),
    ]
