# Generated by Django 5.0.6 on 2024-07-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ananthapuri", "0013_delete_department_page_delete_departments_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
            ],
        ),
    ]
