# Generated by Django 5.0.6 on 2024-07-11 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ananthapuri", "0014_clientdata"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ClientData",
        ),
    ]
