# Generated by Django 5.0.6 on 2024-07-11 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ananthapuri", "0016_contactform"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContactForm",
        ),
    ]
