# Generated by Django 5.0.6 on 2024-08-14 07:21

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ananthapuri", "0019_blog_meta_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="description",
            field=tinymce.models.HTMLField(),
        ),
    ]
